FROM continuumio/anaconda3:2020.02

ENV PYTHONUNBUFFERED 1

WORKDIR /home/bandue

RUN apt-get update && apt-get install -y --no-install-recommends \
  net-tools \
  sudo \
  bzip2 \
  curl \
  gcc \
  git \
  python3-dev \
  vim \
  && \
  apt-get clean && \
  pip install --upgrade pip && \
  conda update -n base conda && \
  conda update --all && \
  conda install -c conda-forge nodejs=10.13.0 && \
  conda clean --all -y && \
  conda install -c anaconda django && \
  conda install -c conda-forge django-filter && \
  conda install -c conda-forge djangorestframework && \
  conda install -c conda-forge djangorestframework-jwt && \
  conda install -c conda-forge django-cors-headers && \
  conda install -c conda-forge django-webpack-loader && \
  conda install -c anaconda python-memcached && \
  conda install -c anaconda psycopg2 && \
  conda install -c conda-forge whitenoise && \
  conda install -c anaconda gunicorn && \
  conda install -c conda-forge dj-database-url && \
  conda install -c conda-forge django-environ && \
  conda install -c conda-forge daphne && \
  python -m pip install -U channels==2.4.0 && \
  pip install channels_redis && \
  pip install dj3-cloudinary-storage && \
  npm install -g yarn && \
  yarn global add add @vue/cli

ENV DJANGO_ENV develop
