# Generated by Django 2.2.5 on 2020-04-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200414_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='day_week',
            field=models.CharField(blank=True, choices=[('WD', 'Weekdays'), ('WE', 'Weekends'), ('AL', 'Always')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='direction',
            field=models.CharField(blank=True, choices=[('OR', 'Original'), ('CO', 'Copy'), ('AL', 'All')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='genre',
            field=models.TextField(blank=True, null=True, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='part',
            field=models.TextField(blank=True, null=True, verbose_name='Part'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='prefecture',
            field=models.IntegerField(blank=True, choices=[(1, 'Hokkaido'), (2, 'Aomori Prefecture'), (3, 'Iwate Prefecture'), (4, 'Miyagi Prefecture'), (5, 'Akita Prefecture'), (6, 'Yamagata Prefecture'), (7, 'Fukushima Prefecture'), (8, 'Ibaraki Prefecture'), (9, 'Tochigi Prefecture'), (10, 'Gunma Prefecture'), (11, 'Saitama Prefecture'), (12, 'Chiba Prefecture'), (13, 'Tokyo Prefecture'), (14, 'Kanagawa Prefecture'), (15, 'Niigata Prefecture'), (16, 'Toyama Prefecture'), (17, 'Ishikawa Prefecture'), (18, 'Fukui Prefecture'), (19, 'Yamanashi Prefecture'), (20, 'Nagano Prefecture'), (21, 'Gifu Prefecture'), (22, 'Shizuoka Prefecture'), (23, 'Aichi Prefecture'), (24, 'Mie Prefecture'), (25, 'Shiga Prefecture'), (26, 'Kyoto Prefecture'), (27, 'Osaka Prefecture'), (28, 'Hyogo Prefecture'), (29, 'Nara Prefecture'), (30, 'Wakayama Prefecture'), (31, 'Tottori Prefecture'), (32, 'Shimane Prefecture'), (33, 'Okayama Prefecture'), (34, 'Hiroshima Prefecture'), (35, 'Yamaguchi Prefecture'), (36, 'Tokushima Prefecture'), (37, 'Kagawa Prefecture'), (38, 'Ehime Prefecture'), (39, 'Kochi Prefecture'), (40, 'Fukuoka Prefecture'), (41, 'Saga Prefecture'), (42, 'Nagasaki Prefecture'), (43, 'Kumamoto Prefecture'), (44, 'Oita Prefecture'), (45, 'Miyazaki Prefecture'), (46, 'Kagoshima Prefecture'), (47, 'Okinawa Prefecture')], null=True),
        ),
    ]
